version: "3.8"  # optional since v1.27.0
services:
  api:
    image: poc-1:latest
    volumes:
      - ./:/prometheus-poc-1
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
    command: bundle exec rails server --port=3000 --binding=0.0.0.0
  sidekiq:
    image: poc-1:latest
    volumes:
      - ./:/prometheus-poc-1
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
volumes:
  redis-data:
  db-data: