version: "3.8"  # optional since v1.27.0
services:
  api:
    image: poc-1:latest
    container_name: poc-1-api
    volumes:
      - ./:/prometheus-poc-1
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
      - redis
      - sidekiq
      - prom-exporter
    command: bundle exec rails server --port=3000 --binding=0.0.0.0
  sidekiq:
    image: poc-1:latest
    container_name: poc-1-sidekiq
    env_file: .env
    volumes:
      - ./:/prometheus-poc-1
    depends_on:
      - db
      - redis
      - prom-exporter
    command: bundle exec sidekiq
  prom-exporter:
    image: poc-1:latest
    container_name: poc-1-prom
    volumes:
      - ./:/prometheus-poc-1
    ports:
      - "9394:9394"
    command: bundle exec prometheus_exporter -p 9394 -b 0.0.0.0
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
volumes:
  redis-data:
  db-data: